name: Dependabot Commenter

on:
  pull_request_target:
    types:
      - labeled

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Dependabot Commenter
        if: |
          (github.event.label.name == ':shipit: merge') && (github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'dependabot-preview[bot]')
        uses: peaceiris/actions-label-commenter@v1.9.1
        with:
          github_token: ${{ secrets.RSG_BOT_TOKEN }}
          config_file: .github/label-commenter-dependabot.yml
