name: Deploy Docs

on:
    push:
        branches:
            - main
        paths:
            - docs/**
            - src/**
            - .github/workflows/deploy-docs.yml
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: pages
    cancel-in-progress: false

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7
              with:
                  clean: 'false'
                  fetch-depth: '0'
            - name: 🛠️ Setup mise
              uses: jdx/mise-action@v4
              with:
                  install: true
                  cache: true
                  github_token: ${{ secrets.GITHUB_TOKEN }}

            - name: 📚 Build docs
              run: mise run docs:build
              env:
                  GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}

            - name: Upload Pages artifact
              uses: actions/upload-pages-artifact@v5
              with:
                  path: docs/dist

    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v5
