name: Lint

on:
    pull_request_target:
        branches:
            - main
            - next
    merge_group:
        branches:
            - main
            - next

permissions:
    actions: read
    checks: write
    contents: write
    deployments: read
    id-token: none
    issues: write
    discussions: none
    packages: none
    pages: none
    pull-requests: write
    repository-projects: none
    security-events: none
    statuses: write

concurrency:
    group: lint-${{ github.event.pull_request.number || github.run_id }}
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
              with:
                  clean: 'false'
                  fetch-depth: '0'
                  ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.sha }}
                  repository: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name || github.repository }}
                  token: ${{ secrets.RSG_BOT_TOKEN }}
            - name: Get Head Commit Message
              id: commit-message
              run: |
                  echo "message=$(git show -s --format=%s)" >> "$GITHUB_OUTPUT"
            - name: 🛠️ Setup mise
              uses: jdx/mise-action@v2
              with:
                  install: true
                  cache: true
            - name: 🧹 Lint (hk fix)
              if: github.event_name == 'pull_request_target'
              run: |
                  hk fix --from-ref "$DEFAULT_BRANCH" --to-ref "$HEAD"
              env:
                  DEFAULT_BRANCH: ${{ github.event.pull_request.base.sha }}
                  HEAD: ${{ github.event.pull_request.head.sha }}
            - name: 🧹 Lint (hk check)
              if: github.event_name == 'merge_group'
              run: |
                  hk check --from-ref "$DEFAULT_BRANCH" --to-ref "$HEAD"
              env:
                  DEFAULT_BRANCH: ${{ github.event.merge_group.base_sha }}
                  HEAD: ${{ github.event.merge_group.head_sha }}
            - name: Add & Commit
              if: github.event_name == 'pull_request_target' && !contains(steps.commit-message.outputs.message, 'Automatically linting code')
              uses: stefanzweifel/git-auto-commit-action@v7
              env:
                  GITHUB_TOKEN: ${{ secrets.RSG_BOT_TOKEN }}
              with:
                  commit_message: Automatically linting code
